name: CorysSpawner
main: de.coryson.corysSpawner.CorysSpawner
description: A simple Plugin for custom spawners
author: Coryson
version: 1.5
api-version: 1.20
commands:
  spawner:
    usage: /spawner <player> <mob>
    description: Gibt dir einen LootSpawner
